---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: debian/buster64
provisioner:
  become: true
  lint:
    name: ansible-lint
verifier:
  name: goss
  lint:
    name: yamllint
