---
name: Ansible Galaxy
on:
  push:
    branches:
      - main
  release:

jobs:
  galaxy:
    name: Ansible Galaxy
    uses: systemli/github-ansible-workflow/.github/workflows/ansible-galaxy-workflow.yaml@main
    secrets:
      galaxy-token: ${{ secrets.galaxy_api_key }}
